-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Erstellungszeit: 12. Sep 2024 um 09:49
-- Server-Version: 10.4.32-MariaDB
-- PHP-Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Datenbank: `anime_manga_daten`
--

-- --------------------------------------------------------

--
-- Tabellenstruktur für Tabelle `anime_manga`
--

CREATE TABLE `anime_manga` (
  `id` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `image_url` varchar(255) NOT NULL,
  `summary` text DEFAULT NULL,
  `rating` int(11) DEFAULT NULL,
  `rank` int(11) DEFAULT NULL,
  `manga` tinyint(1) DEFAULT NULL,
  `Genre` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Daten für Tabelle `anime_manga`
--

INSERT INTO `anime_manga` (`id`, `title`, `image_url`, `summary`, `rating`, `rank`, `manga`, `Genre`) VALUES
(1, 'JoJo\'s Bizarre Adventure', 'https://m.media-amazon.com/images/M/MV5BZDc3NGQ3ZWQtYjNkOC00MjhiLTg2N2YtNmZlOGNiZTFkOWNhXkEyXkFqcGdeQXVyNjc2NjA5MTU@._V1_FMjpg_UX1000_.jpg', 'Jonathan JoJo Joestar is the only heir of the influential Joestar family. Since a carriage accident shortly after his birth in which his mother died, he lives alone with his father until one day Dio Brando enters their lives. Dio is the son of the man who supposedly rescued his father in the aforementioned carriage accident, which took place twelve years ago. Out of gratitude for what he did back then, Dio is now, after his father\'s death, accepted into the Joestar family, where he quickly tries to weaken JoJo\'s position and make his life hell. The story is told of the conflict between Jojo and Dio and how this takes on an unimaginable dimension in later years due to a mysterious stone mask.', 5, 48, 0, 'Fighting-Shounen'),
(2, 'Hunter x Hunter', 'https://aniworld.to/public/img/cover/hunter-x-hunter-stream-cover-MaRyTr2RrYFXcBUsu31xIbkf6jszxJJJ_220x330.jpg', 'Gon\'s greatest desire is to become a Hunter, a guardian of the balance between people and their environment. He wants to find his missing father, who is also a Hunter. Together with his new companions Kurapika, Leorio and Killua, Gon experiences an adventurous story, the extent of which he cannot even imagine during the Hunter Exam...', 5, 60, 0, 'Fighting-Shounen'),
(3, 'Dragonball Super', 'https://aniworld.to/public/img/cover/dragonball-super-stream-cover-cvR5ub9EET6KEq4zVka1VpzNJa1XVISE_220x330.jpg', 'Son Goku and his friends enjoy the quiet life on Earth. But the peaceful idyll is suddenly disturbed when Beerus, the God of Destruction, awakens from a long sleep and shows up at Bulma\'s birthday party with his companion Whis. They have tracked down the last remaining Saiyans, Vegeta and Son Goku, in the hope of finding the Super Saiyan God among them. To Beerus\'s annoyance, the two know nothing about it, even though he had been looking forward to a fight. When Boo then angers him, he swears to wipe out the Earth. Now it is up to Son Goku again to stop the God of Destruction and prevent the planet from being destroyed...', 5, 61, 0, 'Fighting-Shounen'),
(4, 'One Piece', 'https://aniworld.to/public/img/cover/one-piece-stream-cover-l6LlKHG1SE7sGiiNs7X0RkbQQ6hewT0X_220x330.jpg', 'Wealth, power and fame. The man who fought for all of this was Gol D. Roger, the King of the Pirates. When he was executed, his last words were: \"You want my treasure? You can have it! Just look for it! I have hidden the greatest treasure in the world somewhere.\" This treasure is the One Piece and it is somewhere on the Grand Line. This marked the beginning of the great pirate age. Monkey D. Luffy is 17 years old and has a big goal: he wants to become King of the Pirates and find the One Piece treasure! Luffy has received special powers through the devil fruit \"GumGum\" and has become a rubber person. He has a dream about the pirate Shanks, who once saved his life...', 5, 62, 0, 'Fighting-Shounen'),
(5, 'Naruto Shippuden', 'https://aniworld.to/public/img/cover/naruto-shippuden-stream-cover-2wUIuNMOJ5oTb2fHFCsW3sWfRnq64QYA_220x330.jpg', 'Naruto and Jiraiya return from their training trip to Konoha Village. Two and a half years have passed since they left. Naruto, a bad student who was always up to pranks, has become a very good ninja. After various training fights, Tsunade comes up with a plan: Sakura and Naruto should form a team under Kakashi\'s leadership and go on ninja missions as Team Kakashi. Naruto\'s big goal is to lead his friend Sasuke back on the right path.', 5, 63, 0, 'Fighting-Shounen'),
(6, 'Naruto', 'https://aniworld.to/public/img/cover/naruto-stream-cover-KyerU8M7Jb4v3jGANFyBceoHIeG5fKn4_220x330.jpg', 'A huge nine-tailed fox monster attacks the village of Konohagakure and destroys everything in its surroundings. Many brave ninjas die trying to protect their families and defend the village. Finally, a unique ninja manages to tame the demon and seals it in the body of a newborn. However, this hero, the Hokage of the fourth generation, has to pay a high price. He loses his life saving the village. 12 years have passed since this disaster, the boy Naruto Uzumaki, a somewhat clumsy ninja, has just passed his first final exam at the ninja academy. Now that he has passed the first hurdle on the way to becoming a great ninja, he sets out with his two friends to complete many missions for the village. At his side is the young girl Sakura Haruno, with whom Naruto is madly in love, and the young model student Sasuke Uchiha, with whom Sakura is madly in love. This leads to many exciting and funny situations when completing their missions.', 5, 64, 0, 'Fighting-Shounen'),
(7, 'The God of High School', 'https://aniworld.to/public/img/cover/the-god-of-high-school-stream-cover-YZdUtIHAh99nzJXPq4Wy04oTBwdQ8KzM_220x330.jpg', 'Jin Mori calls himself the strongest high schooler of all, and one day he gets the chance to prove it: He is invited to the \"God of High School,\" a tournament that will determine the strongest high schooler and grant the winner absolutely every wish. All participants are powerful fighters, but what awaits him at the end of the tournament? This is just the beginning of a breathtaking series of impressive fights!', 5, 65, 0, 'Fighting-Shounen'),
(8, 'Black Clover', 'https://aniworld.to/public/img/cover/black-clover-stream-cover-WWoAujz6fnp93s8iZ3F9iqqjO7WtXiIV_220x330.jpg', 'Asta and Yuno were once left together at a church. The two were inseparable from childhood, but a rivalry also developed. One of them would become the next king of magicians, that was what they swore to each other, and so their goal was clear. While Yuno turned out to be a genius in the magical arts, Asta was unable to use magic and trained his body to compensate. When Yuno receives a mysterious grimoire that shows a four-leaf clover instead of the usual three-leaf clover, and shortly afterwards finds himself in great danger, Asta\'s true power is suddenly revealed. He obtains the \"Black Clover\" grimoire of anti-magic. With the same goal in mind, the two friends and rivals set out on a journey.', 5, 66, 0, 'Fighting-Shounen'),
(9, 'Bleach', 'https://aniworld.to/public/img/cover/bleach-stream-cover-3zPD5VwzRq15HdsjOSyiaza99umvoY6I_220x330.jpg', '[S17 Thousand Year Blood War] The 15-year-old student Ichigo Kurosaki has had the ability to see ghosts since childhood. One day he meets the Shinigami Rukia Kuchiki, who is hunting a Hollow. As she is seriously injured during the fight, she is forced to transfer her powers to Ichigo so that he can defeat the Hollow in her place. Until Rukia recovers, Ichigo must now do the work of a Shinigami. Rukia enrolls at Ichigo\'s school and moves into his closet. Over time, the two become friends. Since Rukia Kuchiki has exceeded her stay in the human world, Rukia is forcibly brought back to the Soul Society by her stepbrother, the commander of the 6th Division of the 13 Protection Units of the Soul Society Byakuya Kuchiki and the vice commander of the 6th Division Renji Abarai, where all deceased souls, including the Shinigami, live. Because she transferred her Shinigami powers to a human, which is a serious offense, she is sentenced to have her soul erased. Since Ichigo is determined to save Rukia, he lets himself be trained by Kisuke Urahara, who runs a business selling products for spiritual beings and is an extremely experienced former commander of the 12th Division. So he sets off for Soul Society with his friends and schoolmates Yasutora \"Chad\" Sado and Orihime Inoue, who also have special powers, and the Quincy Uryū Ishida, where they confront powerful Shinigami in an attempt to save Rukia. In the process, a plot planned by one or three of Seireitei\'s commanders is uncovered bit by bit, which could have serious consequences, not only for Soul Society, but also for this world, with Karakura, the hometown of the main characters, being explicitly targeted by the conspiracy.', 5, 67, 0, 'Fighting-Shounen'),
(10, 'Dragonball Z', 'https://aniworld.to/public/img/cover/dragonball-z-stream-cover-pnuMY6dEwzVSPBJHxvMbJrHXjzNS5EOm_220x330.jpg', 'Many years have passed since little Son Goku set out to find the legendary Dragon Balls to prevent them from falling into the wrong hands. Now he is a grown man, married and has a young son of his own. One day an alien warrior appears who introduces himself as Son Goku\'s brother Raditz and tells Son Goku that he is not a human at all, but a Saiyan warrior. His mission was to destroy the earth. However, after an accident he lost his memory. Now it is time to carry out the mission. However, Son Goku refuses and goes into battle against new, powerful enemies.', 5, 68, 0, 'Fighting-Shounen'),
(11, 'A Silent Voice', 'https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=85,width=480,height=720/catalog/crunchyroll/c78169bec692d5b9b9f3776df14d8428.jpg', 'Shouya Ishida is the class clown and has already made a name for himself among his classmates and teachers. When the hearing-impaired Shouko Nishimiya moves to his school, it doesn\'t take long until he and his group find a new victim for their teasing and increasingly brutal pranks. When one of Shouko\'s expensive cochlear implants \"disappears\" again, her mother finally demands that something change. The severity of the bullying and the cost of the implants put the teaching staff and school management in turmoil and a culprit was quickly found: Shouya. To escape the bullying, Shouko changes schools again and Shouya, who was abandoned and betrayed by his previous friends, is on his own while he is now the victim of all bullying. So he grows up, alone and with nothing but hatred for all strangers and those who so willingly stabbed him in the back. But he learned from his mistakes and is now trying to make amends for his previous misdeeds: he works part-time outside of school to reimburse his mother for the cost of Shouko\'s implants and he taught himself sign language to officially ask Shouko for forgiveness. However, the road to forgiveness is long and difficult - especially if you have never forgiven yourself.', 5, 59, 0, 'Drama'),
(12, 'Akame ga Kill!', 'https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=85,width=480,height=720/catalog/crunchyroll/8aa257503ef86474dffd0a518bb57d7a.jpg', 'Tatsumi is a young fighter from a poverty-stricken village in the Empire. In order to support his village financially, he sets off for the empire\'s capital with the aim of joining the army. However, when he arrives there, he quickly realizes that the capital is not as magnificent a place as he imagined. Kicked out of the overcrowded barracks and robbed of his savings, Tatsumi is threatened with having to spend his first night in the capital on the streets. Luckily for him, he is picked up by the wealthy girl Aria, who offers him a job as a bodyguard and informs him about the corrupt state of the empire.\r\n\r\n', 5, 58, 0, 'Drama'),
(13, 'Cyberpunk: Edgerunners', 'https://m.media-amazon.com/images/M/MV5BMTQ0MGI4NTgtZTlkNy00YTU5LThjM2ItNDczMGFlZWY2ZWM3XkEyXkFqcGdeQXVyMTM3NDc1OTM2._V1_FMjpg_UX1000_.jpg', 'In a dystopian world full of corruption and cybernetic implants, a talented but ruthless street kid wants to become an outlaw mercenary - an Edgerunner.', 5, 49, 0, 'Fantasy'),
(14, 'Food Wars!', 'https://www.tvtime.com/_next/image?url=https%3A%2F%2Fartworks.thetvdb.com%2Fbanners%2Fposters%2F289909-1.jpg&w=640&q=75', 'Souma Yukihira\'s dream is to become a full-time chef at his father\'s restaurant and surpass his father\'s cooking skills. But just as Souma finishes middle school, his father, Jouichirou Yukihira, closes the restaurant to cook in Europe. Initially dejected, Souma\'s fighting spirit is rekindled by a challenge from his father. He asks him to attend an elite culinary school where only 10% of the students graduate. Can Souma survive this school?', 5, 50, 0, 'Cooking'),
(15, 'Haikyuu!!', 'https://m.media-amazon.com/images/I/811C+xGQwnL.jpg', 'Shouyou Hinata\'s love for volleyball is sparked when he happens to see Karasuno High School\'s national championship game on television. Especially the player nicknamed &quot;Little Titan&quot; He liked it and decided to emulate it. However, the middle school team founded by Hinata only has a few members and yet they somehow managed to make it to their middle school\'s first regular game. In their first and last game, Hinata\'s team is defeated by Tobio Kageyama, the player with the title \"King of the Field\" and his team. Hinata vows to take revenge on Kageyama in high school and begins training hard so that he can be accepted into his dream high school, Karasuno. When he finally joins the volleyball club at Karasuno High School, he gets a big surprise: his arch enemy Kageyama plays on the same team as him!', 5, 51, 0, 'Sports'),
(16, 'I Want to Eat Your Pancreas', 'https://play-lh.googleusercontent.com/SUDOxGhYBT1YRnuxaFkT_XS1fxwgOJvXG0bLNcVKC-HIeiSA8A8odYUUlMqn5t_dutquYIyuvR0Q_XtUkcAA', 'Haruki Shiga is an antisocial loner who prefers to spend his time reading books and is not particularly well respected in his class. Sakura Yamauchi is cheerful and strong in character and is popular with everyone with her open and sunny personality. The two could hardly be more different and yet one day they will become inseparably linked. As Haruki waits to be called in the hospital, he finds a small book - \"Living with Death\" - a diary that describes the daily life of a dying person. It doesn\'t take long before the owner of the book shows up: his classmate Sakura. Sakura suffers from a pancreatic disease and although medical advances allow her to lead an almost normal life, she will soon die. However, this is something that she has kept secret from all her friends so far, because what she needs in this last time on earth is not pity, but real normality - normality, which she finds in Haruki, who now goes from being a \"just classmate\". a “classmate who knows my secret.” Haruki is carried away by Sakura and the more time the two spend together, the more they find themselves caught in a storm of feelings that they cannot explain to themselves. \"Friendship\"? \"Love\"? Such trivial words are not enough to describe the relationship between the two. \"Let\'s enjoy the world until I die, okay?\" - these are her words and so little by little the free spirit Sakura breaks Haruki\'s hard shell and he begins to see the world with different eyes...', 5, 52, 0, 'Drama'),
(17, 'Kuroko’s Basketball', 'https://m.media-amazon.com/images/M/MV5BNjMxMDJkNGQtMDkwMy00ZmQyLThjNWQtODYyODU2MmYwYTA1XkEyXkFqcGdeQXVyMTQ3MjMyMTYz._V1_FMjpg_UX1000_.jpg', 'Taiga Kagami has only just made it to Seirin High School when he already runs into Tetsuya Kuroko. At the time, Kuroko was the secret sixth man of the Teiko middle school basketball team. Together with Taiga, he is now trying to bring his team to the national school basketball championship, and in doing so he is not only faced with his former teammates, who are keeping a critical eye on him.', 5, 53, 0, 'Sports'),
(18, 'My Teen Romantic Comedy', 'https://aniworld.to/public/img/cover/my-teen-romantic-comedy-snafu-stream-cover-WRAZjaPE7xUqFeJIzYrmhNtLNmK6VOI7_220x330.jpg', 'Hachiman Hikigaya is already in his second year of high school, but as a model loner and outsider he has found neither friends nor social connections. But that should now change, says his class teacher Shizuka Hiratsuka, and is more or less forcing him to join a club. This is the “Service Club” and Hachiman is amazed when he finds only one person in the club room: the president and the only member of said club, Yukino Yukinoshita. It quickly becomes clear that, despite her beauty and intelligence, she is not particularly sociable either, and from now on the two of them have to work together, despite their different methods and ideals, and help others in the name of the Service Club in order to perhaps be able to help themselves one day.', 5, 54, 0, 'Romance'),
(19, 'Noragami', 'https://aniworld.to/public/img/cover/noragami-stream-cover-4PF7Ju3lHcLJ6Zjb2d48leUoyIkqjEA2_220x330.jpg', 'Not every god has it easy, especially if he doesn\'t have his own shrine. Without a permanent home, Yato, despite his divine status, is forced to offer his services as a kind of rent-a-god. He draws customers\' attention to himself through advertising doodles and graffiti in public toilets and on the walls of houses and if that wasn\'t depressing enough, his divine weapon would also terminate his service. In this situation, the student Hiyori saves him from an approaching car, but is hit by it herself. Recovered, she tries to find Yato again, but in an incident she discovers that her soul has been between her world and the afterlife since the accident, which means she also has special powers. She decides to work with Yato and help him fight the threat to the people.', 5, 55, 0, 'Fantasy'),
(20, 'Overlord', 'https://aniworld.to/public/img/cover/overlord-stream-cover-omSMCBclvrOeeGJ97217bHKDovVa7qsC_220x330.jpg', 'The story begins with the popular online game Yggdrasil, which will one day be shut down in the year 2138. However, Momonga, the protagonist, doesn\'t want to log out. Momonga is then transformed into a powerful skeleton magician. The world of Yggdrasil then changes, so that NPCs suddenly gain emotions and their own consciousness. Without parents, friends or a place in society, this young man tries to conquer the new world created by the game Yggdrasil.', 5, 56, 0, 'Fantasy'),
(21, 'One Punch Man', 'https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=85,width=480,height=720/catalog/crunchyroll/d8eed44e3d48097ab5fd36b6815fc18e.jpe', 'Saitama is a hero who became a hero just for fun. After special training, he has become so strong that he is practically invincible. However, his abilities seem to frustrate him as he no longer feels the thrill and excitement of fighting a tough battle. This leads him to question his desire for power, which leads him to an existential crisis.', 5, 57, 0, 'Fantasy'),
(22, 'The Dangers in My Heart', 'https://aniworld.to/public/img/cover/the-dangers-in-my-heart-stream-cover-ZgquqCyk9NpgzOau54zyDpChtgSfoe0H_220x330.jpg', 'Kyotaro can barely stay at the bottom rung of his school\'s hierarchy. Who can blame him for accepting to play the tortured lead in a psychological thriller. He spends his days imagining how he can disrupt the peaceful lives of his classmates and pines after the class idol. But Kyotaro isn\'t nearly the troubled teenager he pretends to be... and it turns out Anna\'s a little weird herself!', 5, 69, 0, 'Romance'),
(23, 'The Rising of the Shield Hero', 'https://aniworld.to/public/img/cover/the-rising-of-the-shield-hero-stream-cover-IrA2qGtuU5fYTZLUxlRDVRHm0Wuz1yGZ_220x330.jpg', 'Naofumi Iwatani is actually just a simple otaku, but one day he finds himself in another world. He was summoned as one of the Four Legendary Heroes to save the Empire of Melromarc from ruin. As the hero of the shield, he is supposed to fight alongside his comrades - but they soon stab him in the back and leave him without money, respect and honor. Will he be able to use his purely defensive skills to escape this desperate situation?', 3, 97, 0, 'Adventure'),
(24, 'The Quintessential Quintuplets ', 'https://aniworld.to/public/img/cover/the-quintessential-quintuplets-stream-cover-p2HdlfkgEQSlDPxpwkguPzgn2dl5K6fU_220x330.jpg', 'Since high school student Fuutarou Uesugi is poor but intelligent at the same time, he tries out a job as a tutor that pays surprisingly well. The students he is supposed to teach are his new classmate, Itsuki Nakano - including her four sisters. Not only are the quintuplets chaotic, they also have absolutely no desire to learn, despite their miserable test results. But before they change for the better, Fuutarou must first win the trust of the five sisters.', 5, 70, 0, 'Romance'),
(25, 'Rascal Does Not Dream of Bunny Girl Senpai', 'https://aniworld.to/public/img/cover/rascal-does-not-dream-of-bunny-girl-senpai-stream-cover-ewcxksGtOJcjFLviHQsfbbYyEyQRrHvS_220x330.jpg', 'One day in the library, high school student Sakuta Azusagawa meets a girl in a bunny costume named Mai Sakurajima. It turns out that she is a famous actress and popular child star and goes to the same school as him. But despite her fame and provocative appearance, Sakuta is the only one who can see and hear Mai; For some reason people haven\'t been able to notice Mai for a few days and so she came to the library to check it out. Sakuta wonders whether this could be related to the so-called “puberty syndrome,” a mysterious phenomenon that is rumored to be circulating on the Internet. He decides to get to the bottom of the matter and spends more time with Mai to solve this secret. He gets to know her and her feelings better and also meets other girls with “puberty syndrome”.', 5, 84, 0, 'Romance'),
(26, 'Your Lie in April', 'https://aniworld.to/public/img/cover/your-lie-in-april-stream-cover-Dh4NQ6b0M2mKWei4c5hzugmntqN9WuYh_220x330.jpg', 'Arima Kosei was a well-known piano luminary, but his career ended abruptly when his mother, who was also his piano teacher, died and Kosei\'s world collapsed. Due to the shock, it was impossible for him to perceive tones or the sound of his piano and his world, which was once dominated by music, sank into silence and darkness. Two years later, Kosei is still determined to live a life without music and instead spend his free time with his friends Watari and Tsubaki. But one girl finally throws his resolutions aside: Miyazono Kaori, who is not only beautiful and has an open-hearted personality, but whose style of playing the violin is a reflection of these positive qualities. With her emotional delivery, Kaori leads Kosei back to the world of music and once again shows him its joys', 5, 85, 0, 'Drama'),
(27, 'Terror in Tokio', 'https://aniworld.to/public/img/cover/terror-in-tokio-stream-cover-eO3bHBO2zTcwkMB70fk1N0ZsgwRlEJMi_220x330.jpg', 'The Tokyo of an alternative present is shaken by a spectacular terrorist attack. It was preceded by a bizarre and ignored internet video of two masked teenagers who call themselves Nine and Twelve. Under the name Sphinx, they gave advance information about their crime, a pattern that they now repeat with every subsequent attack. What motivated them to carry out the attacks is unknown, as is why they announced their actions in this cryptic way. The demoted police officer Shibazaki seems to be the only one who can take them on and a game of cat and mouse develops between Sphinx and the police. But while the identity of the terrorists remains unknown to the public, it is discovered by chance by the girl Lisa Mishima. The resulting dangerous acquaintance seems to give Lisa the opportunity to escape from the hell of her everyday life.', 5, 86, 0, 'Thriller'),
(28, 'Assassination Classroom', 'https://aniworld.to/public/img/cover/assassination-classroom-stream-cover-HrhwuyMLiQE1ZI9xhJfz0f4xQBpXlnog_220x330.jpg', 'Earth is threatened by a powerful octopus-like creature that has destroyed 70% of the moon, leaving it forever in the shape of a crescent moon. In addition, this creature announces that the earth will be destroyed within a year if people do not manage to fulfill the task he has set. As a teacher at Kunugigaoka Junior High School, the strange creature now teaches the students of class 3-E, not only in normal subjects, but also in the art of killing. The students\' goal is to kill their Korosensei-Unkillable Teacher (as they call the monster) in order to save the earth. In addition, the government promises 10 billion yen to the student who manages to kill Korosensei. But the undertaking is not an easy one, because the octopus teacher has superhuman strength.', 5, 87, 0, 'Action-Comedy'),
(29, 'Vinland Saga', 'https://aniworld.to/public/img/cover/vinland-saga-stream-cover-kvj59QiJ0zGSobFqvlF9MCrmDiXSHb9g_220x330.jpg', 'Thorfinn is a young and extremely talented Viking warrior who has been able to assert himself several times in Askeladd\'s troops. But Thorfinn\'s heart does not beat for plunder and raids, but rather the fire of revenge burns within him. It was none other than Askeladd himself who robbed Thorfinn of his father and now exploits the boy as part of his Viking troop. In order to finally take revenge for the murder of his father, he wants to defeat Askeladd in an honorable duel, but the young Viking has to earn it first... In order to gain the right to a duel with Askeladd, he has to perform various deeds accomplish this – for example, fulfilling sabotage missions or killing enemy generals.', 5, 88, 0, 'Adventure'),
(30, 'Demon Slayer', 'https://aniworld.to/public/img/cover/demon-slayer-kimetsu-no-yaiba-stream-cover-KxpQFf7c18BoSh94jgSY8bkc1KA3DIqM_220x330.png', 'Tanjiro is the eldest son of a family that lost their father. One day he visits another town to sell charcoal, but instead of going home in the evening, he spends the night at someone\'s house because there is a rumor that a demon haunts the surrounding mountain region at night. When he comes home the next day, he finds that his family has been murdered by a demon. The only survivor of the tragedy is Tanjiro\'s younger sister Nezuko, who has become a demon. In order to make his sister human again and to take revenge on the murderer of his family, the two siblings set out on a journey. An adventure story of blood and swords begins.', 5, 89, 0, 'Fighting-Shounen'),
(31, 'Tokyo Ghoul', 'https://aniworld.to/public/img/cover/tokyo-ghoul-stream-cover-1UXP5kH2v4RrUaN2GYspRmMde8J7woUE_220x330.jpg', 'They live in the middle of Japan\'s capital Tokyo: ghouls that feed on humans. The 18-year-old bookworm Ken has to experience this firsthand when his crush Liz tries to rip his delicious innards out of him on a date. The seriously injured man wakes up shortly afterwards in the hospital - and learns that his attacker\'s organs have been transplanted into him. He quickly realizes that something is wrong with him: normal food smells and tastes spoiled, and he can\'t digest anything he eats. In return, he gets a red eye when he\'s hungry and, much to his chagrin, develops an appetite for human flesh - even for his best friend Hide. Whether Ken wants it or not, his development into a ghoul progresses inexorably...', 5, 90, 0, 'Horror'),
(32, 'Sword Art Online', 'https://aniworld.to/public/img/cover/sword-art-online-stream-cover-vQ6A1IKJL3vNPu3TyXxX8f5GJRRypsGf_220x330.jpg', 'The VRMMORPG (Virtual Reality Massively Multiplayer Online Role-Playing Game) Sword Art Online (SAO) will start on November 6, 2022, the special feature of which is that players can completely immerse themselves in a virtual reality of a medieval fantasy world called Aincrad and through the Replicating all sensory perceptions, having the illusion of actually living in them. This happens because players use a device called NerveGear, which can directly read and stimulate the sensory and motor areas in the brain. Similar to an MMORPG, players can collect experience points by killing monsters that allow them to level up. The following applies: the more powerful the monster, the more experience points the player receives. The higher a player\'s level, the stronger the player is in combat. One of the 10,000 players is student Kazuto Kirigaya under the pseudonym Kirito, who had already taken part in the game\'s beta test. After a while he notices that he can no longer log out and shortly afterwards the developer of the game and the underlying NerveGear technology, Akihiko Kayaba, announces that the players can only leave this world after the final bosses of all 100 levels of Aincrad have been defeated. Death in this world, as well as removing the NerveGear, automatically leads to death in the real world.', 5, 91, 0, 'Action'),
(33, 'Jujutsu Kaisen', 'https://aniworld.to/public/img/cover/jujutsu-kaisen-stream-cover-repX7K4JuFCsuNLaimSSlxjaOomIlZQw_220x330.JPG', 'Hardship, regret, shame: the negative feelings that arise from people\'s hearts become curses that embed themselves in all of our lives. And the only thing that can drive out a curse is another curse. Yūji spends his days like any other student. But one day his friends are attacked by curses and to save them he eats the finger of the two-faced Sukuna. From then on he shares his body with him and joins the Jujutsu Academy to fight against curses. So begins the story of the boy who became a curse to exorcise a curse.', 5, 92, 0, 'Action'),
(34, 'My Hero Academia', 'https://aniworld.to/public/img/cover/my-hero-academia-stream-cover-7tVGmPwXpceHfN6ryKeZVYH5bADdAvi8_220x330.jpg', 'Izuku Midoriya lives in a world where humanity has developed superpowers called Quirks. Unfortunately for him, around 80% of people have such superpowers and Izuku is one of the remaining 20% ​​who were born without Quirks. Determined not to give up on his dream of being a hero, he rushes into applying to the Hero Academy - one of the most prestigious hero schools of all time. This school trains younger people to become superheroes in order to defeat the crooks that roam the world. Luckily, Izuku then catches the eye of history\'s greatest hero: All-Might! He wants to train him from now on so that he can be accepted into his dream school...', 5, 83, 0, 'Fighting-Shounen'),
(35, 'Blue Lock', 'https://aniworld.to/public/img/cover/blue-lock-stream-cover-PJQgXe1drofkNfbfHeTKxLa76AmTBVxY_220x330.jpg', 'Three hundred promising talents will be invited to take part in this special event where there can only be one winner. Yoichi Isagi is also one of the candidates. After depriving his school team of a chance to win the championship by passing the ball to a teammate instead of shooting at the goal himself, he wonders whether his team-oriented style of play is effective enough. Now he is ready to do everything to become a national player. Because anyone who leaves “Blue Lock” will never have the chance to be included in the prestigious team again. Can Yoichi make it and prevail?', 5, 82, 0, 'Sports'),
(36, 'Love is War', 'https://aniworld.to/public/img/cover/kaguya-sama-love-is-war-stream-cover-Tyfu6kJfKZcfIx0MruO35iCuZidh66jh_220x330.jpg', 'Only the most brilliant students go to Shûchiin Academy. The hopes of the world rest on them. One day, Student Council Vice President Kaguya Shinomiya and President Miyuki Shirogane meet in the student office. It seems like they\'ve taken a liking to each other... But six months later, everything is still the same! Both are blinded by their own pride and are just looking for a way to get the other to confess their feelings first. The war has begun!', 5, 73, 0, 'Romance'),
(37, 'Attack on Titan', 'https://aniworld.to/public/img/cover/attack-on-titan-stream-cover-gy1YrBf3uQ8k2I0aAXK9TggID2Kn7Koz_220x330.jpg', 'Several hundred years ago, humanity was almost wiped out by Titans. They are huge, have little intelligence, and seem to eat humans just for fun. A small percentage of humans survived by entrenching themselves in a city with massive walls larger than even the greatest Titans. The city hasn\'t seen a Titan in over 100 years. The young teenager Eren and his foster sister Mikasa have to watch as a super titan appears out of nowhere in front of the city and destroys the walls. While his smaller counterparts invade the city through the holes, the children have to witness the horror of their mother being eaten alive. Eren vows that he will slaughter every single Titan in the world and take revenge for all of humanity.', 5, 74, 0, 'Action'),
(38, 'Fire Force', 'https://aniworld.to/public/img/cover/fire-force-stream-cover-YABtOYerrvqj9VKVLyrImsNUjvADnMYu_220x330.jpg', 'Terror has the metropolis of Tokyo firmly in its grip. Demon-possessed people suddenly began to burst into flames. To combat this phenomenon, a special firefighting team, the Fire Force, was formed, ready to intervene at any time if spontaneous combustion should occur. The team is now joined by Shinra, a boy who is able to run at the speed of a rocket using flames on his feet. Will the Fire Force manage to find and stop the source of the ignition or will the city go down in a sea of ​​flames?', 5, 75, 0, 'Fantasy'),
(39, 'Spy X Family', 'https://aniworld.to/public/img/cover/spy-x-family-stream-cover-RCVQ7bSfaVcfD8HlJTbd744e09DFSwbn_220x330.jpg', 'During a Cold War, even the smallest conflict can become a destructive powder keg - and no one knows this better than secret agent Twilight. Many times he has prevented the already tense relationship between his native Westalis and his neighbor Ostania from escalating. But his latest assignment is tough: he has to obtain compromising material about an Eastern politician. But unfortunately he lives a very withdrawn life and so Twilight has no choice but to get to him through his daughter and her private school. And as if it wasn\'t difficult enough for the socially inexperienced agent to maintain the appearance of being part of an elite family, he unknowingly chooses a professional assassin as his wife, paired with a telepathically gifted adopted daughter. Can the three of them cope with their lives as a fake family without finding out about each other or even triggering a world war?', 5, 76, 0, 'Action-Comedy'),
(40, 'Solo Leveling', 'https://aniworld.to/public/img/cover/solo-leveling-stream-cover-JKPmWrUhngNMpjdKgNYqjD8Fv91bOGi4_220x330.jpg', 'It\'s been over a decade since the \"gates\" - pathways connecting the real world to another dimension - suddenly appeared. Since then, some people have awakened with supernatural powers. These are called Hunters and earn their living by using their powers to conquer the dungeons within the Gates. In this world, the low-ranking Hunter Jinwoo Sung is known as the “weakest hunter in all of humanity.” One day, Jinwoo is fatally injured while trying to conquer a high-level dungeon and at that moment a mysterious quest window appears in front of him. On the verge of death, Jinwoo decides to accept the quest, rise in rank and fight his way to the top of the Hunters.', 5, 77, 0, 'Fantasy'),
(41, 'Vagabond', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-XF5ZpNV2RtvxkD6fkMEd34dlBkMch4pe6w&s', 'In \"The Vagabond,\" Robert Louis Stevenson celebrates the freedom and adventure of a wanderer\'s life. The poem expresses a desire to live independently, embracing nature and rejecting material comforts and societal expectations.', 5, 78, 1, 'Epic Historical Martial arts'),
(42, 'Berserk', 'https://m.media-amazon.com/images/I/71jnEkjX8RL._AC_UF894,1000_QL80_.jpg', 'Berserk is a dark fantasy manga series written and illustrated by Kentarō Miura. The series follows the story of Guts, a mercenary warrior drawn into the world of the God Hand, powerful beings who rule the supernatural realm. The story is set in the Kingdom of Midland, a fictional country inspired by medieval Europe.', 5, 79, 1, 'Dark Fantasy'),
(43, 'Steel Ball Run', 'https://m.media-amazon.com/images/I/715hSpTTzHL._AC_UF894,1000_QL80_.jpg', 'Summary. Steel Ball Run is the seventh part in the JJBA series, and the first set in a new continuity. The part is set in America in 1890 and follows paraplegic jockey Johnny Joestar and Gyro Zeppeli on a cross-country horse race from San Diego to New York for the prize money of $50,000,000.', 5, 80, 1, 'Western'),
(44, 'Monster', 'https://m.media-amazon.com/images/I/815xJbtOVfL._AC_UF1000,1000_QL80_.jpg', 'The story revolves around Kenzo Tenma, a Japanese surgeon living in Düsseldorf, Germany whose life enters turmoil after he gets himself involved with Johan Liebert, one of his former patients, who is revealed to be a psychopathic serial killer.', 5, 71, 1, 'Krimi'),
(45, 'Slam Dunk', 'https://images.thalia.media/-/BF2000-2000/862be56ea77342a19e8396d0c6f376b1/slam-dunk-1-taschenbuch-takehiko-inoue.jpeg', 'The story follows Hanamichi Sakuragi, who falls in love with a girl named Haruko Akagi, and decides to enter the Shohoku High School Basketball Team in order to attract her, as she is already in love with another Shohoku player, Kaede Rukawa.', 5, 72, 1, 'Sports'),
(46, 'Kingdom', 'https://m.media-amazon.com/images/I/81ETzKIUWgL._AC_UF894,1000_QL80_.jpg', 'Kingdom provides a fictionalized account of the Warring States period primarily through the experiences of the war orphan Xin and his comrades as he fights to become the greatest general under the heavens, and in doing so, unifying China for the first time in 500 years.\r\n\r\n', 5, 81, 1, 'Action'),
(47, 'Real', 'https://upload.wikimedia.org/wikipedia/en/5/54/Real_%28manga%29_vol._1.png', 'Plot. The story revolves around three teenagers: Nomiya Tomomi, a high school dropout, Togawa Kiyoharu, an ex-sprinter who now plays wheelchair basketball and Takahashi Hisanobu, a popular leader of the high school\'s basketball team who now finds himself a paraplegic after an accident.', 5, 47, 1, 'Sports'),
(48, '20th Century Boys', 'https://d28hgpri8am2if.cloudfront.net/book_images/onix/cvr9781421535388/naoki-urasawas-20th-century-boys-vol-20-9781421535388_hr.jpg', 'It tells the story of Kenji Endo and his friends, who notice that a cult-leader known only as \"Friend\" is out to destroy the world, and that his cult icon bears a striking resemblance to a symbol developed during their childhoods.', 5, 1, 1, 'Drama'),
(49, 'Kaoru Hana wa Rin to Saku', 'https://preview.redd.it/thoughts-on-kaoru-hana-wa-rin-to-saku-by-far-v0-ay1pmv0s7j7d1.png?auto=webp&s=a063d6897eb0c30f18663eefa02c85b61de22f7f', 'Description. This story takes place in a particular town with two infamous schools in constant dispute: Chidori High, a boys\' school predominantly attended by low-class students with damning grades, and its neighbor Kikyo Girls\' High, with most of its female students coming from wealthy and prestigious families.', 5, 14, 1, 'Romance'),
(50, 'Akira', 'https://m.media-amazon.com/images/I/71SKqtvjBAL._AC_UF1000,1000_QL80_.jpg', 'Akira is a highly acclaimed cyberpunk manga and anime created by Katsuhiro Otomo. It takes place in Neo-Tokyo and revolves around young biker gang leader Kaneda and his friend Tetsuo getting entangled in a secret government/millitary plot.', 5, 15, 1, 'Action'),
(51, 'Goodnight Punpun', 'https://m.media-amazon.com/images/I/917IJDfk36L.jpg', 'A coming-of-age drama story, it follows the life of a child named Onodera Punpun, from his elementary school years to his early 20s, as he copes with his dysfunctional family, love life, friends, life goals and hyperactive mind, while occasionally focusing on the lives and struggles of his schoolmates and family.', 5, 16, 1, 'Drama'),
(52, 'Jumyou wo Kaitotte Moratta. Ichinen ni Tsuki, Ichimanen de.', 'https://cdn.myanimelist.net/images/manga/5/260043.jpg', 'Helpless and struggling for cash, 20-year-old Kusunoki sells the last of his possessions to buy food. Noticing his poverty, an old shop owner directs him to a store that supposedly purchases lifespan, time, and health. While not completely believing the man\'s words, Kusunoki nevertheless finds himself at the address out of desperation and curiosity.', 5, 17, 1, 'Drama'),
(53, 'Umarekawattemo Mata, Watashi to Kekkon shitekuremasu ka', 'https://cdn.myanimelist.net/images/manga/1/211769.jpg', 'Toranosuke Ibuki and his wife Kaoru née Okouchi have been devotedly in love for what has seemed like their entire lives. Now, twenty years later, Toranosuke is bedridden in a hospital, but still, their love perseveres. Together, the infatuated couple reminisce about days gone by—when he proposed, when they first met, their relationships with those around them, and their blissful married life. ', 5, 18, 1, 'Romance'),
(54, 'Yomawari Sensei', 'https://cdn.myanimelist.net/images/manga/2/185367.jpg', 'The author, a high school teacher, recounts his 12 years on \"night patrol\" in Yokohama City, where he comes face to face with youth dealing with issues ranging from self-mutilation to drug abuse.\r\n', 5, 19, 1, 'Drama'),
(55, 'Sayonara Eri', 'https://cdn.myanimelist.net/images/manga/3/263979.jpg', 'Suffering from a terminal illness, Yuuta\'s mother asks him to film her last moments, which he does. From her radiant smile when she is with her family to the times when sickness ravages her body in the hospital, he records hours upon hours of footage. After her passing, Yuuta compiles her life into a movie to screen at his school, deciding to add a bit of fantasy to the ending of his film, Dead Explosion Mother, with a literal explosion!', 5, 20, 1, 'Drama'),
(56, 'The Summer You Were There', 'https://mangadex.org/covers/6ecc62e4-25ad-4102-b0d8-580a8023d2fb/571d1d00-9ab1-44ce-b6ab-aa72584ee2f9.jpg.512.jpg', 'Shizuku Hoshikawa, a high school girl who lives avoiding contact with people, writes a novel which is accidentally read by her classmate Kaori Asaka.\r\nShe loves it but finds out Hoshikawa wasn\'t planning to write anymore due to lack of ideas, to which she ends up saying:\r\n\"Let\'s start going out, you and me… You can write a story about our own love.\"', 5, 21, 1, 'Romance'),
(57, 'Welcome to the Ballroom', 'https://mangadex.org/covers/127d4af7-4062-45ec-afb7-b8cf33deb3db/cea4b868-72f1-4856-8dc1-69c920b394f2.jpg.512.jpg', 'An ordinary middle school student, Fujita Tatara couldn\'t find any objective in life and spent his days idly.\r\nOne day, a group of delinquents picks a fight with him and he is saved by a mysterious man.\r\nAfter that, the man surprisingly takes him to a ballroom dancing class. While being inspired by a girl dancer who goes to that school, Hanaoka Shizuku, and her partner, a genius dancer, Hyoudou Kiyoharu, Tatara starts dedicating his youth to dancesport.', 5, 22, 1, 'Comedy'),
(58, 'The Climber', 'https://cdn.myanimelist.net/images/manga/5/96223.jpg', 'Through pain and arduous effort, one can reach the top of the world. Standing where no man has ever set foot before, there is an exhilarating feeling of success. This is what Mori Buntarou trains, works, and lives for.', 5, 13, 1, 'Sports'),
(59, 'Hachigatsu Kokonoka Boku wa Kimi ni Kuwareru.', 'https://mangadex.org/covers/7f1c253d-9557-4abc-b30b-929d7d8db45e/a7e86b7a-82d8-41a5-8732-69627630134e.jpg.512.jpg', 'In order to eat me, my enigmatic stalker is protecting me from other strange women―\r\n\r\nA high school boy, Sakurai, has a secret he cannot tell anyone: he has been plagued by stalkers since he was a child.\r\nOne day, his classmate, Ueda, suddenly transforms into a monster, revealed to be one of his stalkers.\r\nMiyako, who has always been closely following him, appears and saves him.\r\nShe tells Sakurai that the monsters, commonly known as urban legends in Japan, are after him because they love him.\r\nWhat will be the fate of Sakurai who is loved by countless creatures disguised as beautiful girls?\r\n', 5, 12, 1, 'Drama'),
(60, 'Boruto: Two Blue Vortex', 'https://mangadex.org/covers/0b094aab-0cfb-4837-a49b-7267bdb86bec/1f11c83e-cd32-4c98-a3a3-b522c012dad2.jpg.512.jpg', 'With everyone\'s memories having been altered, Boruto finds himself being hunted by his own village. After escaping with Sasuke, what future awaits Boruto...?', 5, 11, 1, 'Action'),
(61, 'Beat & Motion', 'https://mangadex.org/covers/a69377ee-b842-45f8-983b-0b523b695880/f1091972-3079-43c6-bd48-518069d3c8f7.jpg.512.jpg', 'The winner of the MILLION TAG manga competition! A new era of manga begins with this series about the struggle and joy of creating art. Anime and music collide in this new series about growing up and reaching for your dreams!', 5, 2, 1, 'Music'),
(62, 'Baraou no Souretsu', 'https://mangadex.org/covers/808fdeae-5ea2-4839-8f95-8183dfdddddc/ed9df415-f578-454a-98d5-c82cbb88155a.jpg.512.jpg', 'Richard, the ambitious third son of the House of York, believes he is cursed, damned from birth to eternal darkness. But is it truly fate that sets him on the path to personal destruction? Or his own tormented longings? Based on an early draft of Shakespeare’s Richard III, Aya Kanno’s dark fantasy finds the man who could be king standing between worlds, between classes, between good and evil.\r\n', 5, 3, 1, 'Drama'),
(63, 'Arakawa Under the Bridge\r\n', 'https://mangadex.org/covers/bd5dd062-6fd3-44d4-808a-53ed9a17b580/a7e4c41e-642b-4ed0-b802-00062b15d5e6.jpg.512.jpg', 'Kou, a young \"elite\" man, has a policy of never being in debt to anyone. Unfortunately, he ends up owing Nino, a strange girl who saves his life. The girl, who claims she\'s from Venus and lives under a bridge by the Arakawa river, requests that Kou become her lover to settle the debt. So, Kou ends up living under the bridge with Nino.', 5, 4, 1, 'Comedy'),
(64, 'Ghost Beside Him', 'https://mangadex.org/covers/9c03181b-cb89-4a85-96fd-197da755dd1c/39d30a37-bfd2-45b1-8bc6-b1caa01d95be.jpg.512.jpg', 'A high school student that can see ghosts but pretends not to, and Yuko who is one herself and a bit of a time-waster', 5, 5, 1, 'Comedy'),
(65, 'Piano Duo for the Left Hand', 'https://mangadex.org/covers/ee92a76c-3cb6-497b-8e2a-7c6c73b6e059/9d049873-c43e-4257-b1bc-85de479fb4d2.jpg.512.jpg', 'An encounter with a genius junior high school girl pianist Yuzuki Akari, the center of attention throughout Japan, changes the life of delinquent boy Matoba Shuusuke 180 degrees! This is a story of two people who never give up, no matter what hardships await them, and go on pursuing their dreams!', 5, 6, 1, 'Drama'),
(66, 'Seraph of the End', 'https://aniworld.to/public/img/cover/seraph-of-the-end-stream-cover-H7G2DqD9bqq8Gd91yS1J2QBdouKBehxw_220x330.jpg', 'In 2012, a virus raged across Earth, killing everyone over the age of 13. Immediately afterwards, vampires came out of their dark hiding places to enslave the young human orphans. Now, a few years later, 16-year-old Yuichiro manages to free himself from the clutches of the vampires in a dramatic fight. To avenge the death of his family, he joins the Moon Demon Company, an elite unit of the Japanese Imperial Army that tries to push back the vampire horde with the help of demon weapons.', 5, 7, 0, 'Fantasy'),
(67, 'SHY', 'https://mangadex.org/covers/4809bb6c-1af2-41c5-9291-983027602d7f/07cee817-71dc-4219-9dca-ff5e2d3f4ee3.jpg.512.jpg', 'In the middle of the 21st century, the world was on the brink of World War III. But superheroes from across the globe appeared and helped bring an era of peace. With the crisis averted, the Heroes returned to their home countries where they now help with domestic matters. This is the story about the young Japanese heroine named \"Shy\"…\r\n', 5, 8, 1, 'Action'),
(68, 'Shuumatsu no Valkyrie Chronicle: The Legend of Lu Bu Fengxian, the Flying General', 'https://mangadex.org/covers/a4ba84a7-2e74-4c91-afb4-9b81ef8c1650/dedf2f59-43e4-4ef5-b8e4-f3e02777664f.jpg.512.jpg', 'A spin-off centering on Lu Bu Fengxian.', 5, 9, 1, 'Action'),
(69, 'Nodomoto ni Yoake no Aji', 'https://mangadex.org/covers/1c7fba1b-f9b5-4876-ae4d-64287f7d8727/f81a1a00-a07c-4c17-a565-8c2dfcb9887c.jpg.512.jpg', 'Akemi temporarily going back to his uncle\'s restaurant to help out', 5, 10, 1, 'Romance'),
(70, 'Seiryuu no Magoi\r\n', 'https://mangadex.org/covers/8f040249-2f8b-4a96-8b6c-df8fda0ec067/9ad62654-45d0-4ab8-9d4b-22d8cd0ed54c.png.512.jpg', 'Gouda Magoi is a middle school student with overwhelming physical strength. Taking advantage of this, he turns to violence to make money. He then meets and is confronted by Ono Komomo, a kind-hearted girl from the same school, and Magoi’s life begins to change…', 5, 23, 1, 'Drama'),
(71, 'The Summer Hikaru Died', 'https://m.media-amazon.com/images/I/71aptV4ScXL._AC_UF894,1000_QL80_.jpg', 'This horror manga follows Yoshiki and Hikaru, two boys who live in a rural village, enshadowed by a mountain no one may step on. One year ago, Hikaru vanished onto that mountain. What returned is a mysterious entity who\'s occupied Hikaru\'s body, possessing all his memories, and all his love, for Yoshiki.', 5, 24, 1, 'Horror\r\n'),
(72, 'March Comes In Like a Lion', 'https://m.media-amazon.com/images/M/MV5BMDQwYzEzMTctMmViYi00NTE2LWFjMTItZWY5NGFiNzU0YjcyXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_.jpg', 'It features the life of Rei Kiriyama, an introvert and professional shogi player, who gradually develops both his play and his relationship with others.', 5, 37, 1, 'Romance'),
(73, 'Blue Period', 'https://cdn.myanimelist.net/images/manga/2/204827.jpg', 'Second-year high school student Yatora Yaguchi is bored with his normal life. He studies well and plays around with his friends, but in truth, he does not enjoy either of those activities. Bound by norms, he secretly envies those who do things differently.', 5, 38, 1, 'Drama'),
(74, 'Gachiakuta', 'https://cdn.myanimelist.net/images/manga/1/259583.jpg', 'Living in the slums of a wealthy town, Rudo and his foster father Legto try to coexist with the rest of the town\'s residents, but Rudo despises the wastefulness of the upper class. Ignoring the warnings from those around him, Rudo regularly rummages through the town\'s garbage in search of anything useful or valuable to save from the \"Abyss\"—a massive hole where anything considered trash is dumped, including people. Rudo\'s biological father was one such person, having been thrown into the Abyss after he was accused of murder.', 5, 39, 1, 'Action'),
(75, 'Vanitas no Karte', 'https://cdn.myanimelist.net/images/manga/2/176009.jpg', 'There once lived a vampire known as Vanitas, hated by his own kind for being born under a full blue moon, as most arise on the night of a crimson one. Afraid and alone, he created the \"Book of Vanitas,\" a cursed grimoire that would one day take his vengeance on all vampires; this is how the story goes, at least.', 5, 40, 1, 'Fantasy');
INSERT INTO `anime_manga` (`id`, `title`, `image_url`, `summary`, `rating`, `rank`, `manga`, `Genre`) VALUES
(76, 'Hotaru no Yomeiri', 'https://cdn.myanimelist.net/images/manga/3/283419.jpg', 'Satoko, the eldest daughter of the honorable Kirigaya family, has received many marriage proposals from men captivated by her beauty and grace. However, she has turned them all down due to her secret heart defect. Despite her condition, Satoko is still willing to find a husband to ease her beloved father\'s concerns.', 5, 41, 1, 'Romance'),
(77, 'Gokurakugai', 'https://cdn.myanimelist.net/images/manga/2/271134.jpg', 'Gokurakugai, a bright and bustling working class district with a hidden dark side. In this area without order, Tao and Alma work as troubleshooters for hire. Their missions involve helping a young boy find his lost friend, a person who disappears without a trace, and disfigured animal corpses. All the while, the evil spirits who live in the shadows bring out a different side to these troubleshooters!', 5, 42, 1, 'Action'),
(78, 'Shounen no Abyss', 'https://cdn.myanimelist.net/images/manga/2/232167.jpg', 'Reiji Kurose was born in the countryside, and has spent his life believing he can never leave his town. He cannot leave his mother alone with his shut-in brother and demented grandmother, nor can he escape the clutches of Gen Minegishi, who keeps Reiji at his beck and call. In contrast, his childhood friend Sakuko Akiyama sees past the nothingness of their gloomy town and dreams of the chaotic glamor of Tokyo.', 5, 43, 1, 'Drama'),
(79, 'Marriagetoxin', 'https://cdn.myanimelist.net/images/manga/1/265955.jpg', 'A hitman and a marriage swindler set out on the world\'s most grueling battle for marriage! Gero is a young man from a clan of hitmen, which has been in existence for hundreds of years. As someone who\'s never gone to school and lived his life dealing in the dark side of the business, he considers himself to have \"no prospects with women\" and marriage as \"something not for him.\"', 5, 44, 1, 'Comedy'),
(80, 'Toshokan no Daimajutsushi', 'https://cdn.myanimelist.net/images/manga/3/208938.jpg', 'Throughout civilization, books have been revered. They crystallize knowledge, link the past to the future, and convey thought itself. To protect all sorts of written texts, a man known as the Magus of the Library established the Central Library in Aftzaak—the City of Books.', 5, 45, 1, 'Fantasy'),
(81, 'Gleipnir', 'https://aniworld.to/public/img/cover/gleipnir-stream-cover-mFmJjwGjSLUNrPkRq9u4MdyyAXWT6aPD_220x330.jpg', 'The anime series \"Gleipnir\" is about the student Shuichi Kagaya, who leads an ordinary life in a boring small town until it is turned upside down from one day to the next. Because Shuichi has a secret: he can transform into a monster! One morning he woke up in the form of a large dog with an oversized revolver and a zipper strapped to his back - endowed with incredible strength as well as a keen sense of smell. When his classmate Claire Aoki is in danger, Shuichi decides to save her and share his secret with her. But Claire is looking for monsters herself in the hope of finding her sister. And with her sadistic nature and lack of compassion towards others, she isn\'t afraid to take advantage of Shuichi to achieve her goal.', 5, 36, 0, 'Mystery-Action'),
(82, 'Bungo Stray Dogs', 'https://aniworld.to/public/img/cover/bungo-stray-dogs-stream-cover-Eg1HyqjgeuUNCTioLAutsYL34LnQjY8r_220x330.jpg', 'At the center of the story is a league of literary personalities with supernatural powers. For example, there is Ryūnosuke Akutagawa, who wrote critically acclaimed novels. They served as a source of inspiration, among others, Akira Kurosawa\'s Rashōmon film and the Jigoku Hen arc from Aoi Bungaku Series. Within Bungō Stray Dogs, Akutagawa has the ability to transform his cloak into a monster-like entity, which he then commands. Together the writers form the so-called Armed Detective Agency, which strives to solve mysteries.', 5, 35, 0, 'Mystery-Action'),
(83, 'Kakegurui', 'https://aniworld.to/public/img/cover/kakegurui-stream-cover-UOErFKZN8srK3Z8AX3zG26RDjgJllneV_220x330.jpg', 'At the Hyakkaou private academy for privileged sons and daughters, a strange curriculum determines life. The rich among the rich are not characterized by muscle power or intelligence - no, their careers depend on who can better assess and manipulate their counterparts. So why not focus the entire lesson on gambling? So while the winners at the Hyakkaou Private Academy live like kings, the losers are put through the wringer. However, Yumeko Jabami, the new kid at school, has made it her goal to show the would-be bosses what it really means to play high poker.', 4, 95, 0, 'Gambling'),
(84, 'Kakegurui Twin', 'https://aniworld.to/public/img/cover/kakegurui-twin-stream-cover-GAjKX0T8JgEZ7dZ8Q4MoMUz99PYhnGsK_220x330.jpg', 'A year before Yumeko Jabami starts her private school, Mary Saotome, a girl from an average family, is accepted as a model student at the Hyakkao Private Academy. This school, which is characterized by a strict hierarchical system based on gambling winnings, is attended by many children from well-heeled and influential families. School performance or sporting ability counts for nothing here, but gambling skills count for a lot. Students who accumulate debt due to gambling receive pet status. Can Mary Saotome carve out a future for herself at this gambling-dominated school?', 4, 94, 0, 'Gambling'),
(85, 'Sailor Moon', 'https://aniworld.to/public/img/cover/sailor-moon-stream-cover-N1JKRt7jxnTcXr7lBhfVfTLjAz78IwPM_220x330.jpg', 'Oh my goodness – overslept again! 14-year-old Bunny Tsukino is truly a hopeless case. Although she is full of energy, she does poorly in school and is incredibly scatterbrained. Oh yes, she\'s a crybaby too. However, fate has it that this very girl is chosen to save the universe. At least that\'s what the talking cat Luna, who Bunny meets one day, tells us. Your task is to defeat a mysterious force that threatens the entire galaxy. To do this, she has to find other warriors and go with them on the search for the Moon Princess. With the help of a magic formula, Bunny transforms from now on into Sailor Moon, who fights all villains in the name of the moon. Moonstone, fly and win!', 4, 93, 0, 'Magical Girl'),
(86, 'Sailor Moon Crystal', 'https://aniworld.to/public/img/cover/sailor-moon-crystal-stream-cover-dNpP5UNDWt5XIY5vMimqqGyCPH9GlLkj_220x330.jpg', 'Usagi Tsukino, a slightly awkward, whiny girl in her second year of middle school, one day meets a black cat with a crescent moon symbol on its forehead and transforms into Sailor Moon, the guardian of justice and love. It quickly turns out that this encounter was no coincidence and Usagi - together with the other guardians - is given the task of finding the Illusion Silver Crystal and protecting Princess Serenity. Meanwhile, Beryl, Queen of the Dark Kingdom, also sends her minions to find the Illusion Silver Crystal. A battle for this incredibly powerful crystal seems inevitable.', 5, 25, 0, 'Magical Girl'),
(87, 'Magical Girl Site', 'https://aniworld.to/public/img/cover/magical-girl-site-stream-cover-WJXG7lbPg9ZseXNO9mu0uEZbXHnNnNSe_220x330.jpg', 'The girl Aya is brutally abused every day at school and at home, but her tragic fate takes a turn when a site, Mahou Shoujo Site, appears on her computer screen and welcomes her to the world of Mahou Shoujo. The site also provides her with a staff, which is in her locker the next day. Pushed into a corner by her tormentors, she sees no other way out than using the staff. But their actions have unexpected consequences with dramatic consequences.', 5, 26, 0, 'Horror'),
(88, 'Moriarty the Patriot ', 'https://aniworld.to/public/img/cover/moriarty-the-patriot-stream-cover-fOoXCtRgGfNUmqmR1SMz5ML9OtOFmn6B_220x330.jpg', 'At first glance, William Moriarty looks like the typical aristocrat of the early 20th century, but the eye can be deceiving: he sees himself as a kind of savior and helper to those who don\'t know how to help themselves. But anyone who thinks that he is acting out of pure charity will also be deceived here - Moriarty is acting out of pure self-interest, because the young man is one of the greatest criminal geniuses of his time and his greatest hobby is staging a \"perfect crime\".', 5, 27, 0, 'Mystery'),
(89, 'Death Note', 'https://aniworld.to/public/img/cover/death-note-stream-cover-elQ8qF4soxIQnXy6E9mTq2XXZ5a8W2ay_220x330.jpg', 'One day, the above-average intelligent high school student Light Yagami finds a notebook (Death Note) with which he can kill anyone. All he has to do is write his victim\'s name in the book. At first he uses the book to hunt down criminals, but gradually he uses it more and more to shape the world according to his ideas. This calls the young master detective “L” onto the scene. Since in order to kill someone you need the person\'s real name, \"L\" is forced to find the perpetrator of the mysterious murders before they discover their identity and possibly wipe them out. An exciting game of cat and mouse begins.', 5, 28, 0, 'Thriller'),
(90, 'Code Geass: Lelouch of the Rebellion', 'https://aniworld.to/public/img/cover/code-geass-lelouch-of-the-rebellion-stream-cover-eRcU1koZCoqiBgcYb5RgYKWX5RqWP4EI_220x330.jpg', 'During a joyride with his school friend Rivalz, Lelouch, who goes to Ashford Academy under a false name, is involuntarily drawn into a battle between Japanese resistance fighters and British occupying troops. He meets his childhood friend Suzaku Kururugi again, the son of the last Japanese prime minister, who is now working as a foot soldier for Britain. He frees C.C. from an experimental facility that gave him the Geass shortly before he was shot by a troop of British soldiers. He realizes that as the wielder of his Geass, he is the only one who can change the world, destroy the British Empire, and create a life-friendly environment and protection for his blind, paralyzed sister, Nunnally. After ordering the soldiers to commit suicide, he obtains a Knightmare and takes command of the Japanese fighters. He puts on a disguise and the code name Zero and founds the Order of the Black Knights. This forces the commander and governor general of Japan and 4th heir to the throne of the British Empire, Clovis la Britannia, to resort to the new Knightmare unit Lancelot. However, Lelouch manages to gain access to Clovis&amp;amp;#039; to get the command center and kills him after he unsuccessfully tried to find out who murdered his mother using the Geass. Meanwhile, as the pilot of the Lancelot, Suzaku prevents the Japanese rebels from winning, but is then made the scapegoat for the death of Clovis. Shortly before his execution, he is freed by Lelouch, who coordinates the resistance. However, Suzaku refuses to work with him because, in his opinion, change must come from within, not by force. The result of this disagreement is a war to the death.', 5, 29, 0, 'Thriller'),
(91, 'Angels of death', 'https://aniworld.to/public/img/cover/angels-of-death-stream-cover-8xUplATRw5weFfuwJk5e0cvE28LHuFlh_220x330.jpg', 'When 13-year-old Rachel wakes up, she finds herself in the basement of an abandoned building. She has lost all her memories and doesn\'t know where she is. As she wanders through the building, lonely and dazed, she meets a mysterious boy who introduces himself to her as Zack. He carries a sickle like a Grim Reaper\'s and his entire body is wrapped in bandages. A strange bond gradually develops between Zack and Rachel and together they try to escape from the building in which they are both trapped.', 5, 30, 0, 'Thriller'),
(92, 'Chainsaw man', 'https://aniworld.to/public/img/cover/chainsaw-man-stream-cover-XLo5CTmT4WtWwrhmWBxnGNtYHawsQoYp_220x330.png', 'Denji lives in abject poverty with his only friend: a chainsaw devil named Pochita. His father left him with a huge mountain of debt and since then Denji has been going from one low point to the next. Together with Pochita, he hunts down devils in order to pay off his excessive debts and lead a normal life. Luck is not on his side and so one day Denji is betrayed and stabbed in the back. As his consciousness fades, he enters into a contract with Pochita and is resurrected as the \"Chainsaw Man\" - a man with the heart of a devil.', 5, 31, 0, 'Action-Comedy'),
(93, 'Magi: The Labyrinth of Magic', 'https://aniworld.to/public/img/cover/magi-the-labyrinth-of-magic-stream-cover-6eFkqoBbFpgNl9s3uxsQl9OC4dYgHTyF_220x330.jpg', 'Magi tells the adventures of young Aladdin. He has a magical flute with which he can summon the headless djinn Ugo. Since Aladdin wished that Ugo was his friend, he accompanied him on his travels. Aladdin\'s goal is to unravel the mystery surrounding his identity, about which he knows next to nothing. In addition to Ugo, many other friends that he meets during his travels help him on his adventures.', 5, 32, 0, 'Adventure'),
(94, 'GTO: Great Teacher Onizuka', 'https://aniworld.to/public/img/cover/gto-great-teacher-onizuka-stream-cover-HyYPrp4NfeqxzomWRv7SP4YDQXhaHG8j_220x330.jpg', 'Former teacher scare Eikichi Onizuka makes it his goal to become a teacher himself. His motives? The pretty students! Besides, the 22-year-old is really good for nothing other than fights. Unfortunately, his plan turns out to be much more difficult than initially expected, because there are still the stuffy colleagues and students who try to make their teachers\' lives hell. But Onizuka wouldn\'t be Onizuka if that didn\'t motivate him. After all, he is the GTO, Great Teacher Onizuka!', 5, 33, 0, 'Comedy'),
(95, 'Angel Beats!', 'https://aniworld.to/public/img/cover/angel-beats-stream-cover-2wYj93EMYXVoJCSY106z3EMGHVsNNU76_220x330.jpg', 'When Otonashi wakes up on the grounds of an unfamiliar school, he initially doesn\'t know what\'s going on. Neither the girl with the firearm in her hand who greets him nor the fact that he can\'t remember any detail of his life so far arouses enthusiasm in him. The girl, Yuri, explains to Otonashi that he died and that the school grounds they are on is a world between life and death. She tells him about the Shinda Sekai Sensen, a kind of underground organization to which she and some other inhabitants of this world belong. The members of the SSS are all dead teenagers who refuse to adapt to the school system. Because as soon as you bend to the school rules, you mysteriously disappear from the in-between world.', 3, 96, 0, 'Fantasy'),
(96, 'Black Butler', 'https://aniworld.to/public/img/cover/black-butler-stream-cover-8OqnKFhQ34Msm79RBDhV7XWiZVI0nQls_220x330.jpg', 'At first glance, Sebastian is one thing above all: the perfect butler. From elaborate menus to Old English garden art, there is nothing he cannot accomplish with absolute perfection. And it\'s not a little what Ciel, the last of the House of the Phantomhives, demands from him, as the two share a dark fate. As his young master\'s closest confidant and protector, it is up to him to protect him from the dangers that Ciel is exposed to due to his connections to the dark side of society.', 5, 46, 0, 'Comedy'),
(97, 'Hajime no ippo', 'https://aniworld.to/public/img/cover/fighting-spirit-stream-cover-XDf6Z6C7eu3xAjtmjfScWAuvIPmrSiTn_220x330.jpg', 'Ippo Makunouchi is a very shy student who hardly has any friends and no time to find any because he often has to help his mother with boat rental. At school, Ippo is ignored by his classmates and is bullied and beaten by some. When he is beaten again by his classmates after school one day, the professional boxer Takamura comes to his aid. Impressed by how Takamura makes the thugs flee, Ippo asks himself what it means to be strong. From then on, he trains day after day to become a successful boxer and meets new friends, but also strong rivals.', 5, 34, 0, 'Sports');

--
-- Indizes der exportierten Tabellen
--

--
-- Indizes für die Tabelle `anime_manga`
--
ALTER TABLE `anime_manga`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT für exportierte Tabellen
--

--
-- AUTO_INCREMENT für Tabelle `anime_manga`
--
ALTER TABLE `anime_manga`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=98;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
